// <auto-generated/>
#pragma warning disable CS0618
using AgentOrchestrator.CopilotSdk.Models;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace AgentOrchestrator.CopilotSdk.Copilot.Conversations.Item.Chat
{
    /// <summary>
    /// Builds and executes requests for operations under \copilot\conversations\{conversationId}\chat
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ChatRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::AgentOrchestrator.CopilotSdk.Copilot.Conversations.Item.Chat.ChatRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ChatRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/copilot/conversations/{conversationId}/chat", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::AgentOrchestrator.CopilotSdk.Copilot.Conversations.Item.Chat.ChatRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ChatRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/copilot/conversations/{conversationId}/chat", rawUrl)
        {
        }
        /// <summary>
        /// Sends a chat message to an existing conversation and receives a complete response with Copilot&apos;s answer.
        /// </summary>
        /// <returns>A <see cref="global::AgentOrchestrator.CopilotSdk.Models.CopilotConversation"/></returns>
        /// <param name="body">Request body for sending a chat message</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::AgentOrchestrator.CopilotSdk.Models.CopilotConversation400Error">When receiving a 400 status code</exception>
        /// <exception cref="global::AgentOrchestrator.CopilotSdk.Models.CopilotConversation401Error">When receiving a 401 status code</exception>
        /// <exception cref="global::AgentOrchestrator.CopilotSdk.Models.CopilotConversation403Error">When receiving a 403 status code</exception>
        /// <exception cref="global::AgentOrchestrator.CopilotSdk.Models.CopilotConversation404Error">When receiving a 404 status code</exception>
        /// <exception cref="global::AgentOrchestrator.CopilotSdk.Models.CopilotConversation500Error">When receiving a 500 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::AgentOrchestrator.CopilotSdk.Models.CopilotConversation?> PostAsync(global::AgentOrchestrator.CopilotSdk.Models.ChatRequest body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::AgentOrchestrator.CopilotSdk.Models.CopilotConversation> PostAsync(global::AgentOrchestrator.CopilotSdk.Models.ChatRequest body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPostRequestInformation(body, requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::AgentOrchestrator.CopilotSdk.Models.CopilotConversation400Error.CreateFromDiscriminatorValue },
                { "401", global::AgentOrchestrator.CopilotSdk.Models.CopilotConversation401Error.CreateFromDiscriminatorValue },
                { "403", global::AgentOrchestrator.CopilotSdk.Models.CopilotConversation403Error.CreateFromDiscriminatorValue },
                { "404", global::AgentOrchestrator.CopilotSdk.Models.CopilotConversation404Error.CreateFromDiscriminatorValue },
                { "500", global::AgentOrchestrator.CopilotSdk.Models.CopilotConversation500Error.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::AgentOrchestrator.CopilotSdk.Models.CopilotConversation>(requestInfo, global::AgentOrchestrator.CopilotSdk.Models.CopilotConversation.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Sends a chat message to an existing conversation and receives a complete response with Copilot&apos;s answer.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="body">Request body for sending a chat message</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPostRequestInformation(global::AgentOrchestrator.CopilotSdk.Models.ChatRequest body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPostRequestInformation(global::AgentOrchestrator.CopilotSdk.Models.ChatRequest body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = new RequestInformation(Method.POST, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            requestInfo.SetContentFromParsable(RequestAdapter, "application/json", body);
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::AgentOrchestrator.CopilotSdk.Copilot.Conversations.Item.Chat.ChatRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::AgentOrchestrator.CopilotSdk.Copilot.Conversations.Item.Chat.ChatRequestBuilder WithUrl(string rawUrl)
        {
            return new global::AgentOrchestrator.CopilotSdk.Copilot.Conversations.Item.Chat.ChatRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class ChatRequestBuilderPostRequestConfiguration : RequestConfiguration<DefaultQueryParameters>
        {
        }
    }
}
#pragma warning restore CS0618
