// <auto-generated/>
#pragma warning disable CS0618
using AgentOrchestrator.CopilotSdk.Copilot.Conversations.Item.Chat;
using AgentOrchestrator.CopilotSdk.Copilot.Conversations.Item.ChatOverStream;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace AgentOrchestrator.CopilotSdk.Copilot.Conversations.Item
{
    /// <summary>
    /// Builds and executes requests for operations under \copilot\conversations\{conversationId}
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class WithConversationItemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The chat property</summary>
        public global::AgentOrchestrator.CopilotSdk.Copilot.Conversations.Item.Chat.ChatRequestBuilder Chat
        {
            get => new global::AgentOrchestrator.CopilotSdk.Copilot.Conversations.Item.Chat.ChatRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The chatOverStream property</summary>
        public global::AgentOrchestrator.CopilotSdk.Copilot.Conversations.Item.ChatOverStream.ChatOverStreamRequestBuilder ChatOverStream
        {
            get => new global::AgentOrchestrator.CopilotSdk.Copilot.Conversations.Item.ChatOverStream.ChatOverStreamRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::AgentOrchestrator.CopilotSdk.Copilot.Conversations.Item.WithConversationItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithConversationItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/copilot/conversations/{conversationId}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::AgentOrchestrator.CopilotSdk.Copilot.Conversations.Item.WithConversationItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithConversationItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/copilot/conversations/{conversationId}", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
