// <auto-generated/>
#pragma warning disable CS0618
using AgentOrchestrator.CopilotSdk.Copilot.Conversations;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace AgentOrchestrator.CopilotSdk.Copilot
{
    /// <summary>
    /// Builds and executes requests for operations under \copilot
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class CopilotRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The conversations property</summary>
        public global::AgentOrchestrator.CopilotSdk.Copilot.Conversations.ConversationsRequestBuilder Conversations
        {
            get => new global::AgentOrchestrator.CopilotSdk.Copilot.Conversations.ConversationsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::AgentOrchestrator.CopilotSdk.Copilot.CopilotRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public CopilotRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/copilot", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::AgentOrchestrator.CopilotSdk.Copilot.CopilotRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public CopilotRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/copilot", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
