// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace AgentOrchestrator.CopilotSdk.Models
{
    /// <summary>
    /// Request body for sending a chat message
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ChatRequest : IAdditionalDataHolder, IParsable
    {
        /// <summary>Optional extra context for grounding</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::AgentOrchestrator.CopilotSdk.Models.ContextMessage>? AdditionalContext { get; set; }
#nullable restore
#else
        public List<global::AgentOrchestrator.CopilotSdk.Models.ContextMessage> AdditionalContext { get; set; }
#endif
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>OneDrive/SharePoint files and web search settings</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::AgentOrchestrator.CopilotSdk.Models.ContextualResources? ContextualResources { get; set; }
#nullable restore
#else
        public global::AgentOrchestrator.CopilotSdk.Models.ContextualResources ContextualResources { get; set; }
#endif
        /// <summary>User location information for timezone-aware responses</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::AgentOrchestrator.CopilotSdk.Models.LocationHint? LocationHint { get; set; }
#nullable restore
#else
        public global::AgentOrchestrator.CopilotSdk.Models.LocationHint LocationHint { get; set; }
#endif
        /// <summary>The chat message being sent</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::AgentOrchestrator.CopilotSdk.Models.MessageParameter? Message { get; set; }
#nullable restore
#else
        public global::AgentOrchestrator.CopilotSdk.Models.MessageParameter Message { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::AgentOrchestrator.CopilotSdk.Models.ChatRequest"/> and sets the default values.
        /// </summary>
        public ChatRequest()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::AgentOrchestrator.CopilotSdk.Models.ChatRequest"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::AgentOrchestrator.CopilotSdk.Models.ChatRequest CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::AgentOrchestrator.CopilotSdk.Models.ChatRequest();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "additionalContext", n => { AdditionalContext = n.GetCollectionOfObjectValues<global::AgentOrchestrator.CopilotSdk.Models.ContextMessage>(global::AgentOrchestrator.CopilotSdk.Models.ContextMessage.CreateFromDiscriminatorValue)?.AsList(); } },
                { "contextualResources", n => { ContextualResources = n.GetObjectValue<global::AgentOrchestrator.CopilotSdk.Models.ContextualResources>(global::AgentOrchestrator.CopilotSdk.Models.ContextualResources.CreateFromDiscriminatorValue); } },
                { "locationHint", n => { LocationHint = n.GetObjectValue<global::AgentOrchestrator.CopilotSdk.Models.LocationHint>(global::AgentOrchestrator.CopilotSdk.Models.LocationHint.CreateFromDiscriminatorValue); } },
                { "message", n => { Message = n.GetObjectValue<global::AgentOrchestrator.CopilotSdk.Models.MessageParameter>(global::AgentOrchestrator.CopilotSdk.Models.MessageParameter.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteCollectionOfObjectValues<global::AgentOrchestrator.CopilotSdk.Models.ContextMessage>("additionalContext", AdditionalContext);
            writer.WriteObjectValue<global::AgentOrchestrator.CopilotSdk.Models.ContextualResources>("contextualResources", ContextualResources);
            writer.WriteObjectValue<global::AgentOrchestrator.CopilotSdk.Models.LocationHint>("locationHint", LocationHint);
            writer.WriteObjectValue<global::AgentOrchestrator.CopilotSdk.Models.MessageParameter>("message", Message);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
