// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace AgentOrchestrator.CopilotSdk.Models
{
    /// <summary>
    /// OneDrive/SharePoint files and web search settings
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ContextualResources : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>OneDrive or SharePoint files to use as context</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::AgentOrchestrator.CopilotSdk.Models.FileReference>? Files { get; set; }
#nullable restore
#else
        public List<global::AgentOrchestrator.CopilotSdk.Models.FileReference> Files { get; set; }
#endif
        /// <summary>Web search grounding configuration</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::AgentOrchestrator.CopilotSdk.Models.WebContext? WebContext { get; set; }
#nullable restore
#else
        public global::AgentOrchestrator.CopilotSdk.Models.WebContext WebContext { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::AgentOrchestrator.CopilotSdk.Models.ContextualResources"/> and sets the default values.
        /// </summary>
        public ContextualResources()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::AgentOrchestrator.CopilotSdk.Models.ContextualResources"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::AgentOrchestrator.CopilotSdk.Models.ContextualResources CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::AgentOrchestrator.CopilotSdk.Models.ContextualResources();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "files", n => { Files = n.GetCollectionOfObjectValues<global::AgentOrchestrator.CopilotSdk.Models.FileReference>(global::AgentOrchestrator.CopilotSdk.Models.FileReference.CreateFromDiscriminatorValue)?.AsList(); } },
                { "webContext", n => { WebContext = n.GetObjectValue<global::AgentOrchestrator.CopilotSdk.Models.WebContext>(global::AgentOrchestrator.CopilotSdk.Models.WebContext.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteCollectionOfObjectValues<global::AgentOrchestrator.CopilotSdk.Models.FileReference>("files", Files);
            writer.WriteObjectValue<global::AgentOrchestrator.CopilotSdk.Models.WebContext>("webContext", WebContext);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
