// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace AgentOrchestrator.CopilotSdk.Models
{
    /// <summary>Current state of the conversation</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum CopilotConversation_status
    {
        [EnumMember(Value = "active")]
        #pragma warning disable CS1591
        Active,
        #pragma warning restore CS1591
        [EnumMember(Value = "closed")]
        #pragma warning disable CS1591
        Closed,
        #pragma warning restore CS1591
    }
}
