// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace AgentOrchestrator.CopilotSdk.Models
{
    /// <summary>
    /// A message within a Copilot conversation (user or assistant)
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class CopilotMessage : IAdditionalDataHolder, IParsable
    {
        /// <summary>Optional UI rendering hints (Adaptive Cards format)</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::AgentOrchestrator.CopilotSdk.Models.CopilotMessage_adaptiveCards>? AdaptiveCards { get; set; }
#nullable restore
#else
        public List<global::AgentOrchestrator.CopilotSdk.Models.CopilotMessage_adaptiveCards> AdaptiveCards { get; set; }
#endif
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Optional source citations and references</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::AgentOrchestrator.CopilotSdk.Models.CopilotMessage_attributions>? Attributions { get; set; }
#nullable restore
#else
        public List<global::AgentOrchestrator.CopilotSdk.Models.CopilotMessage_attributions> Attributions { get; set; }
#endif
        /// <summary>ISO 8601 timestamp when message was created</summary>
        public DateTimeOffset? CreatedDateTime { get; set; }
        /// <summary>Unique identifier for the message</summary>
        public Guid? Id { get; set; }
        /// <summary>OData type identifier</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? OdataType { get; set; }
#nullable restore
#else
        public string OdataType { get; set; }
#endif
        /// <summary>Optional data classification metadata</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::AgentOrchestrator.CopilotSdk.Models.CopilotMessage_sensitivityLabel? SensitivityLabel { get; set; }
#nullable restore
#else
        public global::AgentOrchestrator.CopilotSdk.Models.CopilotMessage_sensitivityLabel SensitivityLabel { get; set; }
#endif
        /// <summary>Message content</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Text { get; set; }
#nullable restore
#else
        public string Text { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::AgentOrchestrator.CopilotSdk.Models.CopilotMessage"/> and sets the default values.
        /// </summary>
        public CopilotMessage()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::AgentOrchestrator.CopilotSdk.Models.CopilotMessage"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::AgentOrchestrator.CopilotSdk.Models.CopilotMessage CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::AgentOrchestrator.CopilotSdk.Models.CopilotMessage();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "adaptiveCards", n => { AdaptiveCards = n.GetCollectionOfObjectValues<global::AgentOrchestrator.CopilotSdk.Models.CopilotMessage_adaptiveCards>(global::AgentOrchestrator.CopilotSdk.Models.CopilotMessage_adaptiveCards.CreateFromDiscriminatorValue)?.AsList(); } },
                { "attributions", n => { Attributions = n.GetCollectionOfObjectValues<global::AgentOrchestrator.CopilotSdk.Models.CopilotMessage_attributions>(global::AgentOrchestrator.CopilotSdk.Models.CopilotMessage_attributions.CreateFromDiscriminatorValue)?.AsList(); } },
                { "createdDateTime", n => { CreatedDateTime = n.GetDateTimeOffsetValue(); } },
                { "id", n => { Id = n.GetGuidValue(); } },
                { "@odata.type", n => { OdataType = n.GetStringValue(); } },
                { "sensitivityLabel", n => { SensitivityLabel = n.GetObjectValue<global::AgentOrchestrator.CopilotSdk.Models.CopilotMessage_sensitivityLabel>(global::AgentOrchestrator.CopilotSdk.Models.CopilotMessage_sensitivityLabel.CreateFromDiscriminatorValue); } },
                { "text", n => { Text = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteCollectionOfObjectValues<global::AgentOrchestrator.CopilotSdk.Models.CopilotMessage_adaptiveCards>("adaptiveCards", AdaptiveCards);
            writer.WriteCollectionOfObjectValues<global::AgentOrchestrator.CopilotSdk.Models.CopilotMessage_attributions>("attributions", Attributions);
            writer.WriteDateTimeOffsetValue("createdDateTime", CreatedDateTime);
            writer.WriteGuidValue("id", Id);
            writer.WriteStringValue("@odata.type", OdataType);
            writer.WriteObjectValue<global::AgentOrchestrator.CopilotSdk.Models.CopilotMessage_sensitivityLabel>("sensitivityLabel", SensitivityLabel);
            writer.WriteStringValue("text", Text);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
