// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace AgentOrchestrator.CopilotSdk.Models
{
    /// <summary>
    /// Represents a conversation session with Microsoft 365 Copilot
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class CopilotConversation : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>ISO 8601 timestamp when conversation was created</summary>
        public DateTimeOffset? CreatedDateTime { get; set; }
        /// <summary>Human-readable name for the conversation (empty initially, updated after first message)</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DisplayName { get; set; }
#nullable restore
#else
        public string DisplayName { get; set; }
#endif
        /// <summary>Unique identifier for the conversation</summary>
        public Guid? Id { get; set; }
        /// <summary>Array of messages in the conversation (populated in streaming responses)</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::AgentOrchestrator.CopilotSdk.Models.CopilotMessage>? Messages { get; set; }
#nullable restore
#else
        public List<global::AgentOrchestrator.CopilotSdk.Models.CopilotMessage> Messages { get; set; }
#endif
        /// <summary>Current state of the conversation</summary>
        public global::AgentOrchestrator.CopilotSdk.Models.CopilotConversation_status? Status { get; set; }
        /// <summary>Number of message exchanges in the conversation</summary>
        public int? TurnCount { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::AgentOrchestrator.CopilotSdk.Models.CopilotConversation"/> and sets the default values.
        /// </summary>
        public CopilotConversation()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::AgentOrchestrator.CopilotSdk.Models.CopilotConversation"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::AgentOrchestrator.CopilotSdk.Models.CopilotConversation CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::AgentOrchestrator.CopilotSdk.Models.CopilotConversation();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "createdDateTime", n => { CreatedDateTime = n.GetDateTimeOffsetValue(); } },
                { "displayName", n => { DisplayName = n.GetStringValue(); } },
                { "id", n => { Id = n.GetGuidValue(); } },
                { "messages", n => { Messages = n.GetCollectionOfObjectValues<global::AgentOrchestrator.CopilotSdk.Models.CopilotMessage>(global::AgentOrchestrator.CopilotSdk.Models.CopilotMessage.CreateFromDiscriminatorValue)?.AsList(); } },
                { "status", n => { Status = n.GetEnumValue<global::AgentOrchestrator.CopilotSdk.Models.CopilotConversation_status>(); } },
                { "turnCount", n => { TurnCount = n.GetIntValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteDateTimeOffsetValue("createdDateTime", CreatedDateTime);
            writer.WriteStringValue("displayName", DisplayName);
            writer.WriteGuidValue("id", Id);
            writer.WriteCollectionOfObjectValues<global::AgentOrchestrator.CopilotSdk.Models.CopilotMessage>("messages", Messages);
            writer.WriteEnumValue<global::AgentOrchestrator.CopilotSdk.Models.CopilotConversation_status>("status", Status);
            writer.WriteIntValue("turnCount", TurnCount);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
