// <auto-generated/>
#pragma warning disable CS0618
using AgentOrchestrator.CopilotSdk.Copilot.Conversations.Item;
using AgentOrchestrator.CopilotSdk.Models;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace AgentOrchestrator.CopilotSdk.Copilot.Conversations
{
    /// <summary>
    /// Builds and executes requests for operations under \copilot\conversations
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ConversationsRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the ApiSdk.copilot.conversations.item collection</summary>
        /// <param name="position">The unique identifier of the conversation (GUID format)</param>
        /// <returns>A <see cref="global::AgentOrchestrator.CopilotSdk.Copilot.Conversations.Item.WithConversationItemRequestBuilder"/></returns>
        public global::AgentOrchestrator.CopilotSdk.Copilot.Conversations.Item.WithConversationItemRequestBuilder this[Guid position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("conversationId", position);
                return new global::AgentOrchestrator.CopilotSdk.Copilot.Conversations.Item.WithConversationItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>Gets an item from the ApiSdk.copilot.conversations.item collection</summary>
        /// <param name="position">The unique identifier of the conversation (GUID format)</param>
        /// <returns>A <see cref="global::AgentOrchestrator.CopilotSdk.Copilot.Conversations.Item.WithConversationItemRequestBuilder"/></returns>
        [Obsolete("This indexer is deprecated and will be removed in the next major version. Use the one with the typed parameter instead.")]
        public global::AgentOrchestrator.CopilotSdk.Copilot.Conversations.Item.WithConversationItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                if (!string.IsNullOrWhiteSpace(position)) urlTplParams.Add("conversationId", position);
                return new global::AgentOrchestrator.CopilotSdk.Copilot.Conversations.Item.WithConversationItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::AgentOrchestrator.CopilotSdk.Copilot.Conversations.ConversationsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ConversationsRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/copilot/conversations", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::AgentOrchestrator.CopilotSdk.Copilot.Conversations.ConversationsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ConversationsRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/copilot/conversations", rawUrl)
        {
        }
        /// <summary>
        /// Creates a new conversation session with Microsoft 365 Copilot. Returns a conversation ID used for subsequent chat messages.
        /// </summary>
        /// <returns>A <see cref="global::AgentOrchestrator.CopilotSdk.Models.CopilotConversation"/></returns>
        /// <param name="body">Empty JSON body required by API</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::AgentOrchestrator.CopilotSdk.Models.CopilotConversation401Error">When receiving a 401 status code</exception>
        /// <exception cref="global::AgentOrchestrator.CopilotSdk.Models.CopilotConversation403Error">When receiving a 403 status code</exception>
        /// <exception cref="global::AgentOrchestrator.CopilotSdk.Models.CopilotConversation500Error">When receiving a 500 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::AgentOrchestrator.CopilotSdk.Models.CopilotConversation?> PostAsync(global::AgentOrchestrator.CopilotSdk.Copilot.Conversations.ConversationsPostRequestBody body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::AgentOrchestrator.CopilotSdk.Models.CopilotConversation> PostAsync(global::AgentOrchestrator.CopilotSdk.Copilot.Conversations.ConversationsPostRequestBody body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPostRequestInformation(body, requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "401", global::AgentOrchestrator.CopilotSdk.Models.CopilotConversation401Error.CreateFromDiscriminatorValue },
                { "403", global::AgentOrchestrator.CopilotSdk.Models.CopilotConversation403Error.CreateFromDiscriminatorValue },
                { "500", global::AgentOrchestrator.CopilotSdk.Models.CopilotConversation500Error.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::AgentOrchestrator.CopilotSdk.Models.CopilotConversation>(requestInfo, global::AgentOrchestrator.CopilotSdk.Models.CopilotConversation.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Creates a new conversation session with Microsoft 365 Copilot. Returns a conversation ID used for subsequent chat messages.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="body">Empty JSON body required by API</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPostRequestInformation(global::AgentOrchestrator.CopilotSdk.Copilot.Conversations.ConversationsPostRequestBody body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPostRequestInformation(global::AgentOrchestrator.CopilotSdk.Copilot.Conversations.ConversationsPostRequestBody body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = new RequestInformation(Method.POST, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            requestInfo.SetContentFromParsable(RequestAdapter, "application/json", body);
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::AgentOrchestrator.CopilotSdk.Copilot.Conversations.ConversationsRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::AgentOrchestrator.CopilotSdk.Copilot.Conversations.ConversationsRequestBuilder WithUrl(string rawUrl)
        {
            return new global::AgentOrchestrator.CopilotSdk.Copilot.Conversations.ConversationsRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class ConversationsRequestBuilderPostRequestConfiguration : RequestConfiguration<DefaultQueryParameters>
        {
        }
    }
}
#pragma warning restore CS0618
